# Default values for spring-zuul-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ibmcase/spring-zuul-proxy
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: 
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

resources:
  limits:
    memory: 256Mi
  requests:
    memory: 64Mi

eureka:
  client:
    serviceUrl:
      defaultZone:

spring:
  cloud:
    config:
      enabled: false
      uri:

global:
  useConfigServerBootstrap: false
