# Default values for spring-zuul-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ibmcase/spring-zuul-proxy
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: zuul-proxy
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    memory: 256Mi
  requests:
    memory: 64Mi
eureka:
  service: eureka-server
  port: 8761
  preferIpAddress: true